# Generated by Django 4.1.4 on 2023-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableBB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('sats', models.IntegerField(default=0)),
                ('HDOP', models.FloatField(default=0)),
                ('platform_type', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('t_surf', models.FloatField(default=0)),
                ('t_sub_surf', models.FloatField(default=0)),
                ('turbidity', models.CharField(max_length=200)),
                ('turbidity_mg', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('submergence', models.IntegerField(default=0)),
                ('rough', models.IntegerField(default=0)),
                ('level_plc', models.IntegerField(default=0)),
                ('pwr_v_main', models.FloatField(default=0)),
                ('mdatetime', models.DateTimeField()),
                ('turb_debug', models.CharField(default='empty', max_length=2000)),
                ('frame', models.IntegerField(default=0)),
                ('test', models.CharField(default='empty', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TableRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('sats', models.IntegerField(default=0)),
                ('HDOP', models.FloatField(default=0)),
                ('platform_type', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('t_surf', models.FloatField(default=0)),
                ('t_sub_surf', models.FloatField(default=0)),
                ('ap', models.FloatField(max_length=200)),
                ('hp', models.IntegerField(default=0)),
                ('submergence', models.IntegerField(default=0)),
                ('wl', models.IntegerField(default=0)),
                ('level_plc', models.IntegerField(default=0)),
                ('pwr_v_main', models.FloatField(default=0)),
                ('mdatetime', models.DateTimeField()),
            ],
        ),
    ]
