# Generated by Django 4.1.4 on 2023-02-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STD', models.IntegerField(default=0)),
                ('STR', models.IntegerField(default=0)),
                ('Vbat', models.FloatField(default=0)),
                ('HIT', models.FloatField(default=0)),
                ('HIP', models.FloatField(default=0)),
                ('HIH', models.FloatField(default=0)),
                ('mdatetime', models.DateTimeField()),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('SatNum', models.IntegerField(default=0)),
                ('HDOP', models.FloatField(default=0)),
                ('TTF', models.IntegerField(default=0)),
                ('AP', models.FloatField(default=0)),
                ('APT', models.FloatField(default=0)),
                ('Subm', models.FloatField(default=0)),
                ('T1', models.FloatField(default=0)),
                ('T2', models.FloatField(default=0)),
                ('T3', models.FloatField(default=0)),
                ('T4', models.FloatField(default=0)),
                ('T5', models.FloatField(default=0)),
                ('T6', models.FloatField(default=0)),
                ('T7', models.FloatField(default=0)),
                ('T8', models.FloatField(default=0)),
                ('T9', models.FloatField(default=0)),
                ('T10', models.FloatField(default=0)),
                ('T11', models.FloatField(default=0)),
                ('T12', models.FloatField(default=0)),
                ('T13', models.FloatField(default=0)),
                ('T14', models.FloatField(default=0)),
                ('T15', models.FloatField(default=0)),
                ('T16', models.FloatField(default=0)),
                ('T17', models.FloatField(default=0)),
                ('HP', models.FloatField(default=0)),
            ],
        ),
    ]
