# Generated by Django 4.1.4 on 2023-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_tableab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableab',
            old_name='TTF',
            new_name='TTFF',
        ),
    ]
