# Generated by Django 4.1.4 on 2023-02-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_rename_ttf_tableab_ttff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableab',
            name='mdatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablebb',
            name='mdatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablerb',
            name='mdatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
