# Generated by Django 4.1.4 on 2023-02-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_tableab_mdatetime_alter_tablebb_mdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableab',
            name='mdatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tablebb',
            name='mdatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tablerb',
            name='mdatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
