# Generated by Django 4.1.4 on 2023-03-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_tableabdefective_tableab_imei'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableABDefective',
        ),
    ]
