# Generated by Django 4.1.4 on 2023-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_tableab_fmtid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableab',
            name='IMEI',
            field=models.TextField(default=0),
        ),
    ]
