# Generated by Django 4.1.4 on 2023-03-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_delete_tablebb_delete_tablerb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableab',
            old_name='Longtitude',
            new_name='Longitude',
        ),
    ]
