# Generated by Django 4.1.4 on 2023-03-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_rename_longtitude_tableab_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableab',
            name='T10',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T11',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T12',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T13',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T14',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T15',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T16',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T17',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T2',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T3',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T4',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T5',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T6',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T7',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T8',
        ),
        migrations.RemoveField(
            model_name='tableab',
            name='T9',
        ),
    ]
