# Generated by Django 4.1.4 on 2023-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_remove_tableab_t10_remove_tableab_t11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableIceST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormatID', models.IntegerField(default=0)),
                ('IMEI', models.TextField(default=0)),
                ('STD', models.IntegerField(default=0)),
                ('STR', models.IntegerField(default=0)),
                ('Vbat', models.FloatField(default=0)),
                ('HIT', models.FloatField(default=0)),
                ('HIP', models.FloatField(default=0)),
                ('HIH', models.FloatField(default=0)),
                ('mdatetime', models.DateTimeField(null=True)),
                ('Latitude', models.FloatField(default=0)),
                ('Longitude', models.FloatField(default=0)),
                ('SatNum', models.IntegerField(default=0)),
                ('HDOP', models.FloatField(default=0)),
                ('TTFF', models.IntegerField(default=0)),
                ('AP', models.FloatField(default=0)),
                ('APT', models.FloatField(default=0)),
                ('Subm', models.FloatField(default=0)),
                ('T1', models.FloatField(default=0)),
                ('HP', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tableab',
            name='T10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T14',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T15',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T16',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T17',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tableab',
            name='T9',
            field=models.FloatField(default=0),
        ),
    ]
