# Generated by Django 4.1.4 on 2023-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_tableicebtc11_tablepermafrost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableWeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StID', models.IntegerField(default=0)),
                ('Num', models.IntegerField(default=0)),
                ('mdatetime', models.DateTimeField(null=True)),
                ('Latitude', models.FloatField(default=0)),
                ('Longitude', models.FloatField(default=0)),
                ('AP', models.FloatField(default=0)),
                ('APT', models.FloatField(default=0)),
                ('AT', models.FloatField(default=0)),
                ('WS', models.FloatField(default=0)),
                ('WD', models.FloatField(default=0)),
                ('WSmax', models.FloatField(default=0)),
                ('HT', models.FloatField(default=0)),
                ('Vbat', models.FloatField(default=0)),
                ('TD', models.FloatField(default=0)),
            ],
        ),
    ]
