# Generated by Django 4.1.4 on 2023-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_tableweatherstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.IntegerField(default=0)),
                ('mdatetime', models.DateTimeField(null=True)),
                ('Latitude', models.FloatField(default=0)),
                ('Longitude', models.FloatField(default=0)),
                ('sats', models.IntegerField(default=0)),
                ('platform_type', models.TextField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('t_surf', models.FloatField(default=0)),
                ('level_plc', models.FloatField(default=0)),
                ('pwr_v_main', models.FloatField(default=0)),
            ],
        ),
    ]
