# Generated by Django 4.1.4 on 2023-04-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_tablemarker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablemarker',
            old_name='Latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='tablemarker',
            old_name='Longitude',
            new_name='lon',
        ),
    ]
