# Generated by Django 4.1.4 on 2023-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_rename_latitude_tablemarker_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemarker',
            name='HDOP',
            field=models.FloatField(default=0),
        ),
    ]
