# Generated by Django 4.1.4 on 2023-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_tablemarker_datetime_from_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemarker',
            name='datetime_from_email',
        ),
        migrations.AddField(
            model_name='tableweatherstation',
            name='datetime_from_email',
            field=models.DateTimeField(null=True),
        ),
    ]
