# Generated by Django 4.1.4 on 2023-04-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_remove_tablemarker_datetime_from_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablemarker',
            old_name='lat',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='tablemarker',
            old_name='lon',
            new_name='Longitude',
        ),
    ]
