# Generated by Django 4.2.5 on 2023-09-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_rename_lat_tablemarker_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAT500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.IntegerField(default=0)),
                ('Latitude', models.FloatField(default=0)),
                ('Longitude', models.FloatField(default=0)),
                ('sats', models.IntegerField(default=0)),
                ('HDOP', models.FloatField(default=0)),
                ('platform_type', models.TextField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('AT500_temp', models.FloatField(default=0)),
                ('AT500_cond', models.FloatField(default=0)),
                ('AT500_salt', models.FloatField(default=0)),
                ('AT500_density', models.FloatField(default=0)),
                ('AT500_tds', models.FloatField(default=0)),
                ('AT500_turb', models.FloatField(default=0)),
                ('AT500_Ph', models.FloatField(default=0)),
                ('AT500_redox', models.FloatField(default=0)),
                ('AT500_oxygen', models.FloatField(default=0)),
                ('Subm', models.FloatField(default=0)),
                ('level_plc', models.FloatField(default=0)),
                ('pwr_v_main', models.FloatField(default=0)),
                ('mdatetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
