# Generated by Django 4.2.5 on 2023-09-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_tableat500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableat500',
            name='rough',
            field=models.FloatField(default=0),
        ),
    ]
